package SigmaEC.operate;

import SigmaEC.represent.Individual;
import java.util.List;

/**
 * Takes a set of parent individuals and creates a child.
 * 
 * @author Eric 'Siggy' Scott
 */
public interface Procreator<T extends Individual>
{
    /** @return An individual generated by mating a set of parents. */
    public T produceOffspring(List<T> parents);
    
    /** @return The number of parents needed to create a child. */
    public int getNumParents();
    
    /** Representation invariant.  If this returns false, there is something
     * invalid about the Individual's internal state. */
    public boolean repOK();
}
